name: ChitChat
main: com.minecarts.chitchat.ChitChat
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBQuery]
description: An improved chat plugin
commands:
    join:
        description: "Join a channel by it's name"
        usage: "/join [channel name]"
permissions:
    chitchat.channel.chat:
        description: "Allow a player to chat in a channel"
        default: true
    chitchat.channel.join:
        description: "Allow a player to join channels"
        default: true