name: ChitChat
main: com.minecarts.chitchat.ChitChat
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBQuery]
description: An improved chat plugin
commands:
    channel:
        aliases: [ch]
        description: The main command to access all BarrensChat internal commands
        usage: /<command>
    whisper:
        aliases: [w,msg,t,m,tell]
        description: Privately message a player
        usage: /<command> [player] [msg]
    say:
        aliases: [s]
        description: Chat with players nearby
        usage: /<command> [msg]
    join:
        description: Join a channel by its name
        usage: /<command> [channel]
    leave:
        description: Leave a given channel
        usage: /<command> [channel]
    reply:
        aliases: [r]
        description: Respond to the last person to whisper you
        usage: /<command> [msg]
    rewhisper:
        aliases: [rw]
        description: Resends a whisper to the last person you whispered
        usage: /<command> [msg]
    ignore:
        aliases: [unignore]
        description: Toggle if you see a players messages or not
        usage: /<command> [player]
    mute:
        aliases: [gag]
        description: Remove the ability for a player to send messages to global channels
        usage: /<command> [player] [durration]
    unmute:
        aliases: [ungag]
        description: Ungag a player who has been previously gagged
        usage: /<command> [player]
    announce:
        aliases: [broadcast]
        description: Announce to the announcement channel
        usage: /<command> [msg]
    hint:
        aliases: [tip]
        description: Give a hint to a player
        usage: /<command> [player] [msg]
permissions:
    chitchat.admin.*:
        description: "Access to all ChitChat admin commands"
        children:
            chitchat.admin.reload: true
            chitchat.admin.chat: true
            chitchat.admin.mute: true
            chitchat.admin.list: true
            chitchat.admin.force_join: true
            chitchat.ignore.immunity: true
            chitchat.announcement.chat: true
            chitchat.admin.hint: true
    chitchat.admin.hint:
        description: "Issue hints to players"
        default: op
    chitchat.admin.reload:
        description: "Reload all channel setting configuration settings"
        default: op
    chitchat.admin.chat:
        description: "Allows a player to chat in administrative channels"
        default: op
    chitchat.admin.list:
        description: "List another players channels"
        defualt: op
    chitchat.admin.force_join:
        description: "Force join a player to a channel"
        defualt: op
    chitchat.admin.mute:
        description: "Mute other players in global channels"
        defualt: op
    chitchat.channel.join:
        description: "Allow a player to join channels"
        default: true
    chitchat.local.range:
        description: "Show the range in local chat channels"
        default: false
    chitchat.ignore.immunity:
        description: "Grants immunity from being able to be /ignored"
        default: op
    chitchat.announcement.chat:
        description: "Allows chatting in the announcement channel"
        default: op